=== FernandoGuardado/CSCI-3916-Web-API/Movies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://sample" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="movies" type="sam:moviesType" xmlns:sam="http://sample"/>
  <xs:complexType name="moviesType">
    <xs:sequence>
      <xs:element type="sam:movieType" name="movie" minOccurs="0" maxOccurs="unbounded" xmlns:sam="http://sample"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ActorType">
    <xs:sequence>
      <xs:element name="Name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:date" name="DateOfBirth"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="movieType">
    <xs:sequence>
      <xs:element name="Title">
          <xs:simpleType>
              <xs:restriction base="xs:string">
                  <xs:minLength value="1"/>
              </xs:restriction>
          </xs:simpleType>
      </xs:element>
      <xs:element type="xs:gYear" name="Year"/>
      <xs:element name="Genre">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Action"/>
            <xs:enumeration value="Adventure"/>
            <xs:enumeration value="Comedy"/>
            <xs:enumeration value="Drama"/>
            <xs:enumeration value="Fantasy"/>
            <xs:enumeration value="Horror"/>
            <xs:enumeration value="Mystery"/>
            <xs:enumeration value="Thriller"/>
            <xs:enumeration value="Western"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="sam:ActorType" name="Actor" maxOccurs="unbounded" xmlns:sam="http://sample"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== FernandoGuardado/CSCI-3916-Web-API/Assignment 0/Movies.xml
<?xml version="1.0"?>
<movies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://sample"
        xsi:schemaLocation="http://sample Movies.xsd">
    <movie>
        <Title>Spider-Man: Homecoming</Title>
        <Year>2017</Year>
        <Genre>Fantasy</Genre>
        <Actor>
            <Name>Tom Holland</Name>
            <DateOfBirth>1996-06-01</DateOfBirth>
        </Actor>
        <Actor>
            <Name>Zendaya</Name>
            <DateOfBirth>1996-09-01</DateOfBirth>
        </Actor>
    </movie>
    <movie>
        <Title>Logan</Title>
        <Year>2017</Year>
        <Genre>Drama</Genre>
        <Actor>
            <Name>Hugh Jackman</Name>
            <DateOfBirth>1968-10-12</DateOfBirth>
        </Actor>
        <Actor>
            <Name>Patrick Stewart</Name>
            <DateOfBirth>1940-07-13</DateOfBirth>
        </Actor>
    </movie>
    <movie>
        <Title>Harry Potter and the Deathly Hallows - Part 2</Title>
        <Year>2011</Year>
        <Genre>Fantasy</Genre>
        <Actor>
            <Name>Daniel Radcliff</Name>
            <DateOfBirth>1989-07-23</DateOfBirth>
        </Actor>
    </movie>
</movies>
